* Start as daemon
[[https://www.emacswiki.org/emacs/EmacsAsDaemon][Wiki: Emacs as daemon]]
** Add service
~~/.config/systemd/user/emacs.service~
#+begin_src bash
  [Unit]
  Description=Emacs text editor
  Documentation=info:emacs man:emacs(1) https://gnu.org/software/emacs/

  [Service]
  Type=forking
  ExecStart=/usr/bin/emacs --daemon
  ExecStop=/usr/bin/emacsclient --eval "(kill-emacs)"
  Environment=SSH_AUTH_SOCK=%t/keyring/ssh
  Restart=on-failure

  [Install]
  WantedBy=default.target
#+end_src
** Enable the unit
#+begin_src bash
  systemctl enable --user emacs
  systemctl start --user emacs
#+end_src
* Startup
** Startup message
#+begin_src emacs-lisp
;; Hide startup message
(setq inhibit-startup-message t)

;; Startup time
;; (add-hook 'emacs-startup-hook (lambda () (message (emacs-init-time))))
#+end_src
** Dashboard
#+begin_src emacs-lisp
(use-package dashboard
  :init
  :config
  (dashboard-setup-startup-hook))

(setq initial-buffer-choice (lambda () (get-buffer-create "*dashboard*")))

(setq dashboard-set-navigator t)

;; Set the title
;;(setq dashboard-banner-logo-title (format-time-string "%Y-%m-%d"))

;; Set the banner
(setq dashboard-startup-banner 'official)
;; Value can be
;; 'official which displays the official emacs logo
;; 'logo which displays an alternative emacs logo
;; 1, 2 or 3 which displays one of the text banners
;; "path/to/your/image.gif", "path/to/your/image.png" or "path/to/your/text.txt" which displays whatever gif/image/text you would prefer

;; Content is not centered by default. To center, set
(setq dashboard-center-content t)

;; To disable shortcut "jump" indicators for each section, set
;;(setq dashboard-show-shortcuts nil)


(setq dashboard-projects-switch-function 'counsel-projectile-switch-project-by-name)

(setq dashboard-items '((recents  . 5)
    		            (projects . 5)))
#+end_src
* Theme
#+begin_src emacs-lisp
  ;; Main typeface
  (set-face-attribute 'default nil :family "Source Code Pro 13" :height 130)

  ;; Proportionately spaced typeface
  (set-face-attribute 'variable-pitch nil :family "Source Serif Pro" :height 1.0)

  ;; Monospaced typeface
  (set-face-attribute 'fixed-pitch nil :family "Source Code Pro" :height 1.5)

  ;; (set-face-attribute 'default nil :font "Source Code Pro 13" )
  ;; (set-frame-font "Source Code Pro 13" nil t)
  (use-package modus-themes
    :ensure t
    :config
    ;; Add all your customizations prior to loading the themes
    (setq modus-themes-italic-constructs t
	  modus-themes-bold-constructs t
	  modus-themes-tabs-accented nil
	  modus-themes-paren-match '(bold intense)
	  modus-themes-org-blocks 'nil ; {nil,'gray-background,'tinted-background}
	  modus-themes-mode-line '( (padding . 1) (height . 0.9))
	  modus-themes-region '(bg-only no-extend))

    ;; Load the theme files before enabling a theme
    ;; (modus-themes-load-themes)
    (load-theme 'modus-operandi t)            ; Light theme

    (custom-set-faces
     '(whitespace-tab ((t (:background "#F8F8F8" :foreground "#ccc")))))
    ;; :bind ("<f5>" . modus-themes-toggle)
    )

  ;; (custom-set-faces '(whitespace-tab ((t (:background "#fbf8ef" :foreground "#624956")))))
#+end_src
* Use-package extras
#+begin_src emacs-lisp
  (use-package diminish)
#+end_src
* UI
** Modeline
#+begin_src emacs-lisp
  ;; (setq mode-line-format nil)
  (setq-default
   mode-line-format
	(list
	 mode-line-front-space
	 ;; coding system
	 ;; mode-line-mule-info
	 ;; mode-line-client
	 ;; mode-line-modified
	 '(:eval
	   (if (buffer-modified-p)
	       "✒"
	     (if buffer-read-only
		 "ꙭ"
	       " "
	       )))
	 '(:eval
	   (when-let (vc vc-mode)
	     (list " "
		   (propertize (substring vc 5))
		   ;; " in "
		   ;; (let ((path (file-name-directory buffer-file-name)))
		   ;; (vc-call-backend (vc-responsible-backend path) 'root path))
	   )))
	 ;; mode-line-remote
	 mode-line-frame-identification
	 mode-line-buffer-identification
	 mode-line-front-space
	 mode-line-position
	 mode-line-modes
	 mode-line-misc-info
	 mode-line-end-spaces

	 ;; spaces to align right
	 ;; '(:eval (propertize
		  ;; " " 'display
		  ;; `((space :align-to (- (+ right right-fringe right-margin)
		  ;; 		      ,(+ 10 (string-width
		  ;; 			     (if (listp mode-name)
		  ;; 				 (car mode-name)
		  ;; 			       mode-name))))))))
	 ;; the current major mode
	 ;; " %m "
	 ))
#+end_src
** Toolbars and Titlebar
Set titlebar show icon when buffer is modified and display absolute file path when avaialble otherwise, use buffer name.
#+begin_src emacs-lisp
  (setq frame-title-format
    '((:eval (if (buffer-file-name)
		  (abbreviate-file-name (buffer-file-name))
		    "%b"))
      (:eval (if (buffer-modified-p)
		 " 💾  "))
      " | Emacs")
    ;; Allow for frame to be resized when frame size doesn't fit wm/de needs
	frame-resize-pixelwise t
	default-directory "~/")
  ;; Hide toolbar but make sure menubar is shown
  (tool-bar-mode -1)
  (menu-bar-mode -1)
  (scroll-bar-mode -1)
#+end_src
** Show lines and columns
#+begin_src emacs-lisp
  ;; show current line number in the bottom
  (line-number-mode 1)
  ;; show current column in the bottom
  (column-number-mode 1)
#+end_src
** Cursor
#+begin_src emacs-lisp
  (global-hl-line-mode t)

  (use-package beacon
    :init
    (beacon-mode 1))

  (use-package multiple-cursors
    :bind
    ;; Based on continuous lines
    ("C-S-c C-S-c" . mc/edit-lines)
    ;; Based on keywords in the buffer,
    ;; first mark the word, then add more cursors
    ("C->" . mc/mark-next-like-this)
    ("C-<" . mc/mark-previous-like-this)
    ("C-c C-<" . mc/mark-all-like-this)
    ;; Originally return key was bound to C-j, use return key please
    (:map mc/keymap
	  ("<return>" . nil)))
#+end_src
** Generic
#+begin_src emacs-lisp
  ;; Dedicated autosaved directory
  (setq backup-directory-alist
	`(("." . ,(concat user-emacs-directory "backups"))))

  (defalias 'yes-or-no-p 'y-or-n-p)

  (global-prettify-symbols-mode t)

  (add-hook 'window-setup-hook 'toggle-frame-maximized t)

  (use-package minimap
    :config
    (setq minimap-window-location "right")
    (setq minimap-major-modes '(prog-mode org-mode)))

  (use-package which-key
    :diminish
    :init
    (which-key-mode))

#+end_src

** Transpose frame

#+begin_src emacs-lisp
  (use-package transpose-frame)
#+end_src
* Variables
#+begin_src emacs-lisp
  (setq compile-command "nice make -j$(nproc) run")
#+end_src
* Text manipulation
#+begin_src emacs-lisp
    (put 'downcase-region 'disabled nil)
    (put 'upxocase-region 'disabled nil)
    (setq auto-complete-mode 1)
    (use-package auto-complete-rst
      :init
      (add-hook 'rst-mode (lambda () (auto-complete-rst-init))))
#+end_src
#+begin_src emacs-lisp
  (defun pps/show-unique-words (&optional alphabetical)
    "Collect all of the unique words in the current buffer and
  display them in a new buffer.  With prefix, alphabetize the
  list."
    (interactive "P")
    (let ((buf (buffer-name))
	  (new (get-buffer-create "*Unique Words*"))
	  (txt (delete-dups (mapcar #'downcase
				    (split-string (buffer-string)
						  nil nil
						  "[^[:alnum:]]+")))))
      (with-current-buffer new
	(delete-region (point-min) (point-max))
	(insert (format "%d unique words in the <%s> buffer:\n\n"
			(length txt) buf))
	(cl-dolist (word (if alphabetical (sort txt #'string<) txt))
	  (insert (concat word "\n"))))
      (pop-to-buffer new)))

  (fset 'online-clean-unotoolbutton-css
   (kmacro-lambda-form [?\C-a ?\C-s ?. ?u ?n ?o ?â ?\C-b ?\C-w ?\C-s ?C ?o ?n ?t ?r ?o ?l ?. ?J ?S ?D ?â ?â ?\C-b ?\C-k ?\C-n] 0 "%d"))

  (defun pps/delete-duplicate-lines
      (beg end keep &optional reverse adjacent keep-blanks interactive)
    (interactive
     (progn
       (barf-if-buffer-read-only)
       (list (region-beginning) (region-end)
	     (read-string "Keep lines matching regexp: ") ; Prompt for regexp to keep
	     (equal current-prefix-arg '(4))
	     (equal current-prefix-arg '(16))
	     t                                            ; Keep blanks by default
	     t)))
    (let ((lines (unless adjacent (make-hash-table :test 'equal)))
	  line prev-line
	  (count 0)
	  (beg (copy-marker beg))
	  (end (copy-marker end)))
      (save-excursion
	(goto-char (if reverse end beg))
	(if (and reverse (bolp)) (forward-char -1))
	(while (if reverse
	       (and (> (point) beg) (not (bobp)))
		 (and (< (point) end) (not (eobp))))
	  (setq line (buffer-substring-no-properties
		  (line-beginning-position) (line-end-position)))
	  (if (or (and keep-blanks (string= "" line))
		  (string-match keep line))               ; Ignore line if it
							  ; matches regexp to keep
	      (forward-line 1)
	    (if (if adjacent (equal line prev-line) (gethash line lines))
		(progn
		  (delete-region (progn (forward-line 0) (point))
				 (progn (forward-line 1) (point)))
		  (if reverse (forward-line -1))
		  (setq count (1+ count)))
	      (if adjacent (setq prev-line line) (puthash line t lines))
	      (forward-line (if reverse -1 1))))))
      (set-marker beg nil)
      (set-marker end nil)
      (when interactive
	(message "Deleted %d %sduplicate line%s%s"
		 count
		 (if adjacent "adjacent " "")
		 (if (= count 1) "" "s")
		 (if reverse " backward" "")))
      count))

#+end_src
** Use Emacs everywhere
[[https://github.com/tecosaur/emacs-everywhere][Instructions on GitHub page]]
Allow editing stuff from system wide input fields
*** Ensure you have the following dependencies satisfied: xclip, xdotool, xprop, and xwininfo.
*** Add custom global shortcut to the system: emacsclient --eval "(emacs-everywhere)"
#+begin_src emacs-lisp
    (use-package emacs-everywhere)
#+end_src
*** Emacs keybinds in other applications
**** Set Emacs Key themme in gtk2
***** Edit '~/.gtkrc-2.0' and add up top:
#+begin_src xml
  ##### Add Emacs keybindings
  # https://forum.kde.org/viewtopic.php?t=123695
  gtk-key-theme-name="Emacs"
  #
  # Override/tweak the Emacs theme with my settings below.
  #
  binding "gtk-emacs-override"
  {
     unbind "<ctrl>b"
     unbind "<ctrl>i"
     unbind "<ctrl>u"
  }
  class "*" binding "gtk-emacs-override"
  ######
#+end_src
**** [[https://shallowsky.com/blog/linux/gtk3-emacs-key-theme.html][Set Emacs key theme in gtk3]]
***** edit '~/.config/gtk-3.0/settings.ini' and add, inside the [Settings] section, this line:
#+begin_src xml
gtk-key-theme-name = Emacs
#+end_src
***** Set gsetttings:
#+begin_src bash
  gsettings set org.gnome.desktop.interface gtk-key-theme "Emacs"
#+end_src
** Subword
Use =M-b= and =M-f= to navigate, not only between words,
but when present between **subWords**
#+begin_src emacs-lisp
  (global-subword-mode 1)
#+end_src
** Copy whole word
No need to have a function to kill the whole word I find that M-f M-del suffices
#+begin_src emacs-lisp
  (defun pps/copy-whole-word (&optional subword)
    (interactive)
    (save-excursion
      (forward-char 1)
      (if (equal subword 1)
	  (global-subword-mode 0)
	  (global-superword-mode 1))
      (backward-word)
      (kill-word 1)
      (if (equal subword 1)
	  (global-superword-mode 0)
	  (global-subword-mode 1))
      (yank))
    (if (equal subword 1)
	(message "SubWord copied")
      (message "Whole word copied")))
  (global-set-key (kbd "C-c w") 'pps/copy-whole-word)
  (global-set-key (kbd "C-c C-w") (lambda () (interactive) (pps/copy-whole-word 1)))
#+end_src
** Copy whole line
[[https://www.emacswiki.org/emacs/CopyingWholeLines][wiki: Copy whole lines]]
#+begin_src emacs-lisp
  (defun pps/copy-line (arg)
    "Copy lines (as many as prefix argument) in the kill ring"
    (interactive "p")
    (kill-ring-save (line-beginning-position)
		    (line-beginning-position (+ 1 arg)))
    (message "%d line%s copied" arg (if (= 1 arg) "" "s")))

  (global-set-key "\C-c\C-k" 'pps/copy-line)
#+end_src
* Config edit/reload
** Edit
#+begin_src emacs-lisp
  (defun pps/config-visit ()
    (interactive)
    (find-file "~/.emacs.d/config.org"))
  (global-set-key (kbd "C-c e") 'pps/config-visit)
#+end_src
** Reload
#+begin_src emacs-lisp
  (defun config-reload ()
    (interactive)
    (org-babel-load-file (expand-file-name "~/.emacs.d/config.org")))
  (global-set-key (kbd "C-c r") 'config-reload)
#+end_src
* Org
** Structure Template
Reset existent **org-structure-template-alist** variable
to add additional ~src emacs-lisp~ and have =s= trigger that
instead of triggering =src= (=src= gets now assigned to =S=)
More info: =C-h v= and type ~org-structure-template-alist~ =RET=
#+begin_src emacs-lisp
  (setq org-structure-template-alist
      '(("a" . "export ascii")
	("c" . "center")
	("C" . "comment")
	("e" . "example")
	("E" . "export")
	("h" . "export html")
	("l" . "export latex")
	("q" . "quote")
	("S" . "src")
	("s" . "src emacs-lisp")
	("v" . "verse")))

  (setq org-src-preserve-indentation t)
#+end_src
** Org Bullets
#+begin_src emacs-lisp
  (use-package org-bullets
    :config
    (add-hook 'org-mode-hook (lambda () (org-bullets-mode))))
#+end_src
** Org binds
#+begin_src emacs-lisp
    (use-package org
      :bind (("C-c C-k" . 'pps/copy-line)
	     :map org-mode-map
	     ;; Re-bind it so pps/copy-line can use C-c C-k
	     ("C-S-c C-S-k" . org-kill-note-or-show-branches)
	 ("C-c C-k" . 'pps/copy-line)
  ))
#+end_src

* IDO
** Enable ido mode
#+begin_src emacs-lisp
  (setq ido-enable-flex-matching nil)
  (setq ido-create-new-buffer 'always)
  (setq ido-everywhere t)
  (ido-mode 1)
#+end_src
** Make ido vertical
#+begin_src emacs-lisp
  (use-package ido-vertical-mode
    :init
    (ido-vertical-mode 1))
  (setq ido-vertical-define-keys 'C-n-and-C-p-only)
#+end_src
** Using IDO for buffers see "Buffers"
** SMEX
#+begin_src emacs-lisp
  (use-package smex
    :init (smex-initialize)
    :bind
    ("M-x" . smex))
#+end_src
* Buffers
** Create scractch buffer
[[https://www.emacswiki.org/emacs/RecreateScratchBuffer][wiki: Recreate Scractch buffer]]
#+begin_src emacs-lisp
  (defun create-scratch-buffer nil
     "create a scratch buffer"
     (interactive)
     (switch-to-buffer (get-buffer-create "*scratch*"))
     (lisp-interaction-mode))
#+end_src
** Create shell buff
[[http://stackoverflow.com/a/4116113/446256][Taken from stackoverflow]]
#+begin_src emacs-lisp
  (defun pps/spawn-shell (name)
    (interactive "MName of shell buffer to create: ")
    (pop-to-buffer (get-buffer-create (generate-new-buffer-name name)))
    (shell (current-buffer)))
#+end_src
** Kill buffers
[[https://www.youtube.com/watch?v=crDdqZWgZw8&t=227s][Emacs Tutorial 11 - Fixing Emacs Part 2 @4m30]]
Kill the current buffer **without** confirmation:
#+begin_src emacs-lisp
  (defun kill-curr-buffer ()
    (interactive)
    (kill-buffer (current-buffer)))

  (global-set-key (kbd "C-x k") 'kill-curr-buffer)
#+end_src
** Enable iBuffer
#+begin_src emacs-lisp
  (global-set-key (kbd "C-x b") 'ibuffer)
#+end_src
** Switch buffer with IDO
#+begin_src emacs-lisp
  (global-set-key (kbd "C-x C-b") 'ido-switch-buffer)
#+end_src

* Windows
** Switch-window
to do
** Open buffer in
#+begin_src emacs-lisp
  (use-package window
    :ensure nil ; The option use-package-always-ensure is on so better add this for built-in packages
    :preface
    (defun pps/split-win-v ()
      (interactive)
      (split-window-vertically)
      (other-window 1))
    (defun pps/split-win-h ()
      (interactive)
      (split-window-horizontally)
      (other-window 1))
    (defun pps/move-shell-win-r ()
      (interactive)
      (delete-windows-on "*shell*")
	  (display-buffer-in-side-window (get-buffer "*shell*") '((side . right))))
    (defun pps/move-scratch-win-r ()
      (interactive)
      (delete-windows-on "*scratch*")
	  (display-buffer-in-side-window (get-buffer "*scratch*") '((side . right))))
    (defun pps/move-shell-win-b ()
      (interactive)
      (delete-windows-on "*shell*")
	  (display-buffer-in-side-window (get-buffer "*shell*") '((side . bottom))))
   :custom
    (display-buffer-alist
     '(("\\*e?shell\\*"
	(display-buffer-in-side-window)
	(window-height . 0.25)
	(side . bottom)
	;; negative to the left; 0 center; positive to the right
	(slot . -1))
       ("\\*\\(Backtrace\\|Warnings\\|Compile-log\\|[Hh]elp\\|Messages\\)\\*"
	(display-buffer-in-side-window)
	(window-height . 0.25)
	(side . bottom)
	(slot . -0))))
    :bind (("s-n" . next-buffer)
	   ("s-p" . previous-buffer)
	   ("s-o" . other-window)
	   ("s-2" . pps/split-win-v)
	   ("s-3" . pps/split-win-h)
	   ("s-k" . delete-window)
	   ("s-1" . delete-other-windows)
	   ("s-5" . delete-frame)
	   ("<f8>" . window-toggle-side-windows)
	   ("<f9>" . window-swap-states)
	   ("s-#" . pps/move-shell-win-r)
	   ("s-@" . pps/move-shell-win-b)
	   ("s-8" . pps/move-scratch-win-r)))

#+end_src
* Avy
#+begin_src emacs-lisp
  (use-package avy
    :bind
    ("M-s" . avy-goto-char))
#+end_src

* Development
** Generic
#+begin_src emacs-lisp
   (diminish 'auto-revert-mode)
   ;; Auto-closing pairs
   (electric-pair-mode 1)

  ;; WARNING: This will change your life
  ;; (OPTIONAL) Visualize tabs as a pipe character - "|"
  ;; This will also show trailing characters as they are useful to spot.
  (setq whitespace-style '(face tabs tab-mark trailing))

  ;; delete trailing whitespace before save
  (add-hook 'before-save-hook 'delete-trailing-whitespace)

  ;; Expand region increases the selected region by semantic units. Just keep pressing the key until it selects what you want.
  (use-package expand-region
    :bind ("C-=" . er/expand-region))
#+end_src
** Tabs and Spaces
#+begin_src emacs-lisp
  (use-package whitespace
    :diminish
    :config
      (global-whitespace-mode)) ; Enable whitespace mode everywhere

  ;; Our Custom Variable
  (setq custom-tab-width 4)

  (defun disable-tabs () (setq indent-tabs-mode nil))
  (defun enable-tabs  ()
    (local-set-key (kbd "TAB") 'tab-to-tab-stop)
    (setq indent-tabs-mode t)
    (setq tab-width custom-tab-width))

  ;; Language-Specific Tweaks
  (add-hook 'prog-mode-hook 'enable-tabs)
  (add-hook 'prog-mode-hook 'display-line-numbers-mode)
  (add-hook 'lisp-mode-hook 'disable-tabs)
  (add-hook 'emacs-lisp-mode-hook 'disable-tabs)

  ;; Making electric-indent behave sanely
  (setq-default electric-indent-inhibit t)

  ;; Make the backspace properly erase the tab instead of
  ;; removing 1 space at a time.
  (setq backward-delete-char-untabify-method 'hungry)
#+end_src
*** Shift tabulation in selected region
[[https://www.emacswiki.org/emacs/IndentingText][wiki: Indenting Text]]
#+begin_src emacs-lisp
  ;; Shift the selected region right if distance is postive, left if
  ;; negative
  (defun shift-region (distance)
    (let ((mark (mark)))
      (save-excursion
	(indent-rigidly (region-beginning) (region-end) distance)
	(push-mark mark t t)
	;; Tell the command loop not to deactivate the mark
	;; for transient mark mode
	(setq deactivate-mark nil))))

  (defun shift-right ()
    (interactive)
    (shift-region 1))

  (defun shift-left ()
    (interactive)
    (shift-region -1))

  ;; Bind (shift-right) and (shift-left) function to your favorite keys. I use
  ;; the following so that Ctrl-Shift-Right Arrow moves selected text one
  ;; column to the right, Ctrl-Shift-Left Arrow moves selected text one
  ;; column to the left:

  (global-set-key [C-S-right] 'shift-right)
  (global-set-key [C-S-left] 'shift-left)
#+end_src
** Languages

*** IDE Features with lsp-mode

**** lsp-mode

We use the excellent [[https://emacs-lsp.github.io/lsp-mode/][lsp-mode]] to enable IDE-like functionality for many different programming languages via "language servers" that speak the [[https://microsoft.github.io/language-server-protocol/][Language Server Protocol]].  Before trying to set up =lsp-mode= for a particular language, check out the [[https://emacs-lsp.github.io/lsp-mode/page/languages/][documentation for your language]] so that you can learn which language servers are available and how to install them.

The =lsp-keymap-prefix= setting enables you to define a prefix for where =lsp-mode='s default keybindings will be added.  I *highly recommend* using the prefix to find out what you can do with =lsp-mode= in a buffer.

The =which-key= integration adds helpful descriptions of the various keys so you should be able to learn a lot just by pressing =C-c l= in a =lsp-mode= buffer and trying different things that you find there.

#+begin_src emacs-lisp
  ;; To set the garbage collection threshold to high (100 MB) since LSP client-server communication generates a lot of output/garbage
  (setq gc-cons-threshold 800000)
  ;; To increase the amount of data Emacs reads from a process
  (setq read-process-output-max (* 1024 1024))

  (use-package lsp-mode
    :commands (lsp lsp-deferred)
    :init
    (setq lsp-keymap-prefix "C-c l")  ;; Or 'C-l', 's-l'
    :config
    (setq lsp-headerline-breadcrumb-enable 1)
    (lsp-enable-which-key-integration t)
    ;; :hook ((css-mode . lsp-deferred)
    ;;    (typescript-mode . lsp-deferred)
    ;;    (javascript-mode . lsp-deferred)
    ;;    (js-mode . lsp-deferred)
    ;;    (c++-mode . lsp-deferred)))
    :hook ((c-mode . lsp-deferred)
	 (c++-mode . lsp-deferred)
	 (typescript-mode . lsp-deferred)
	 (javascript-mode . lsp-deferred)
	 (js-mode . lsp-deferred)
	 (css-mode . lsp-deferred)))
#+end_src

#+RESULTS:
| (lambda nil (js:flycheck:lsp:next-checkers '(css-stylelint)) (setq flycheck-stylelintrc (locate-user-emacs-file ../.stylelintrc.json))) | lsp-deferred |

**** lsp-ui

[[https://emacs-lsp.github.io/lsp-ui/][lsp-ui]] is a set of UI enhancements built on top of =lsp-mode= which make Emacs feel even more like an IDE.  Check out the screenshots on the =lsp-ui= homepage (linked at the beginning of this paragraph) to see examples of what it can do.

#+begin_src emacs-lisp

  (use-package lsp-ui
    :hook (lsp-mode . lsp-ui-mode)
    :config
    (setq lsp-ui-doc-enable nil)
    (setq lsp-lens-enable t)
    (setq lsp-ui-sideline-show-code-actions t)
    (setq lsp-ui-sideline-show-diagnostics t)
    (setq lsp-ui-sideline-show-code-actions t)
    '(lsp-ui-doc-position 'bottom))

#+end_src

**** lsp-treemacs

[[https://github.com/emacs-lsp/lsp-treemacs][lsp-treemacs]] provides nice tree views for different aspects of your code like symbols in a file, references of a symbol, or diagnostic messages (errors and warnings) that are found in your code.

Try these commands with =M-x=:

- =lsp-treemacs-symbols= - Show a tree view of the symbols in the current file
- =lsp-treemacs-references= - Show a tree view for the references of the symbol under the cursor
- =lsp-treemacs-error-list= - Show a tree view for the diagnostic messages in the project

This package is built on the [[https://github.com/Alexander-Miller/treemacs][treemacs]] package which might be of some interest to you if you like to have a file browser at the left side of your screen in your editor.

#+begin_src emacs-lisp

  (use-package lsp-treemacs
    :after lsp)

#+end_src

*** TypeScript

This is a basic configuration for the TypeScript language so that =.ts= files activate =typescript-mode= when opened.  We're also adding a hook to =typescript-mode-hook= to call =lsp-deferred= so that we activate =lsp-mode= to get LSP features every time we edit TypeScript code.

#+begin_src emacs-lisp

  (use-package typescript-mode
    :mode "\\.ts\\'"
    :hook (typescript-mode . lsp-deferred)
    :config
    (setq typescript-indent-level 2))

#+end_src

*Important note!*  For =lsp-mode= to work with TypeScript (and JavaScript) you will need to install a language server on your machine.  If you have Node.js installed, the easiest way to do that is by running the following command:

#+begin_src shell :tangle no

npm install -g typescript-language-server typescript

#+end_src

This will install the [[https://github.com/theia-ide/typescript-language-server][typescript-language-server]] and the TypeScript compiler package.

*** Bash
Install this to use LSP in shell scripts
#+begin_src shell :tangle no
npm install -g bash-language-server
#+end_src

** Flycheck
LSP current breaks Flycheck's "next-checker" feature. Flycheck is able to
daisy-chain multiple syntax checkers, running one after the other. You can run
src_emacs-lisp[:export code]{(flycheck-verify-setup)} and have a look at each
entry's "next checkers." However, the checker supplied by LSP, =lsp=, runs in
many different modes and doesn't have any "next checkers." Flycheck wasn't
designed to allow a single checker to have different "next checkers" depending
on the mode of the current buffer. From [[https://github.com/sangster/emacs/blob/master/README.org#flycheck-integration][here]].

See [[https://github.com/flycheck/flycheck/issues/1762][flycheck issue #1762: "Correct way to chain checkers to lsp"]].

To implement the hack-fix, from the above link, we need to set LSP's
"next-checker" in the new =flycheck-local-checkers= variable in a hook for each
mode, like:
#+begin_src emacs-lisp
  (defvar-local flycheck-local-checkers nil
    "Buffer-local Flycheck checkers.")

  (defun js:advice-around:flycheck-checker-get(fn checker property)
    (or (alist-get property (alist-get checker flycheck-local-checkers))
	(funcall fn checker property)))

  (advice-add 'flycheck-checker-get
	      :around #'js:advice-around:flycheck-checker-get)

  (defun js:flycheck:lsp:next-checkers (checkers)
    "Set CHECKERS as the LSP checker's next-checkers in the local buffer."
    (setq flycheck-local-checkers `((lsp . ((next-checkers . ,checkers))))))
#+end_src
*** CSS
#+begin_src emacs-lisp
  (add-hook
   'css-mode-hook
   (lambda ()
     (js:flycheck:lsp:next-checkers '(css-stylelint))
     (setq flycheck-stylelintrc
	   (locate-user-emacs-file "../.stylelintrc.json"))))
#+end_src
** Company Mode

[[http://company-mode.github.io/][Company Mode]] provides a nicer in-buffer completion interface than =completion-at-point= which is more reminiscent of what you would expect from an IDE.  We add a simple configuration to make the keybindings a little more useful (=TAB= now completes the selection and initiates completion at the current location if needed).

We also use [[https://github.com/sebastiencs/company-box][company-box]] to further enhance the look of the completions with icons and better overall presentation.

#+begin_src emacs-lisp

  (use-package company
    :diminish
    :hook ((lsp-mode . company-mode)
	   (sgml-mode . company-mode)
	   (emacs-lisp-mode . company-mode)
	   (nxml-mode . company-mode)
	   (shell-mode . company-mode)
	   (eshell-mode . company-mode))
    :bind (:map company-active-map
	   ("<tab>" . company-complete-selection))
    :after lsp-mode
    :bind (:map lsp-mode-map
	   ("<tab>" . company-indent-or-complete-common))
    :custom
    (company-minimum-prefix-length 1)
    (company-idle-delay 0.0))

  (use-package company-box
    :diminish
    :hook (company-mode . company-box-mode))

#+end_src

** Projectile

[[https://projectile.mx/][Projectile]] is a project management library for Emacs which makes it a lot easier to navigate around code projects for various languages.  Many packages integrate with Projectile so it's a good idea to have it installed even if you don't use its commands directly.

#+begin_src emacs-lisp

  (use-package projectile
    :diminish projectile-mode
    :config (projectile-mode)
    :bind-keymap
    ("C-c p" . projectile-command-map)
    :init
    ;; NOTE: Set this to the folder where you keep your Git repos!
    (when (file-directory-p "~/LibreOffice")
      (setq projectile-project-search-path '("~/LibreOffice")
	    projectile-globally-ignored-directories
		  (append '("node_modules" "dist" "po" "L10n" "log" "test"))))
    (setq projectile-switch-project-action #'projectile-dired))

  (use-package counsel-projectile
    :config (counsel-projectile-mode))

#+end_src

** Commenting
From [[https://www.emacswiki.org/emacs/CommentingCode][wiki: Commenting Code]] but with my own key combination
#+begin_src emacs-lisp
  ;; Original idea from
  ;; http://www.opensubscriber.com/message/emacs-devel@gnu.org/10971693.html
  (defun comment-dwim-line (&optional arg)
    "Replacement for the comment-dwim command.
    If no region is selected and current line is not blank and we are not at the end of the line,
    then comment current line.
    Replaces default behaviour of comment-dwim, when it inserts comment at the end of the line."
      (interactive "*P")
      (comment-normalize-vars)
      (if (and (not (region-active-p)) (not (looking-at "[ \t]*$")))
	  (comment-or-uncomment-region (line-beginning-position) (line-end-position))
	(comment-dwim arg)))

  (global-set-key "\M-/" 'comment-dwim-line)
#+end_src

** Rainbow Delimiters

[[https://github.com/Fanael/rainbow-delimiters][rainbow-delimiters]] is useful in programming modes because it colorizes nested parentheses and brackets according to their nesting depth.  This makes it a lot easier to visually match parentheses in Emacs Lisp code without having to count them yourself.

#+begin_src emacs-lisp
  (use-package rainbow-mode
    :diminish)

  (use-package rainbow-delimiters
    :hook (prog-mode . rainbow-delimiters-mode))

#+end_src
** Magit
*** Magit setup
#+begin_src emacs-lisp
  (use-package magit
    :init
    :bind (("C-x g" . magit-status)))
#+end_src
*** Use spell checker
#+begin_src emacs-lisp
  (add-hook 'git-commit-setup-hook 'git-commit-turn-on-flyspell)
#+end_src
** Rest client
#+begin_src emacs-lisp
  (use-package restclient
    :mode ("\\.http\\'" . restclient-mode))
#+end_src
